### PR TITLE
chore: change error message in case of empty response from API

### PR DESCRIPTION
**Pull request by crazydevlegend**
changed error message in case of empty response (as mog asked)

### CODE REVIEW

**Comment by salahawk** [comment]
I see, you changed the error message only.
I wonder if you really don't need to touch API integration part due to the changes with the `text` endpoint

**Comment by crazydevlegend** [comment]
> I see, you changed the error message only. I wonder if you really don't need to touch API integration part due to the changes with the `text` endpoint

i made default settings of the `text` endpoint to work for the chat app.
so it works as it should.

**Comment by salahawk** [comment]
> > I see, you changed the error message only. I wonder if you really don't need to touch API integration part due to the changes with the `text` endpoint
> 
> i made default settings of the `text` endpoint to work for the chat app. so it works as it should.

Where can I see the working demo?

**Comment by salahawk** [comment]
> > > > I see, you changed the error message only. I wonder if you really don't need to touch API integration part due to the changes with the `text` endpoint
> > > 
> > > 
> > > i made default settings of the `text` endpoint to work for the chat app. so it works as it should.
> > 
> > 
> > Where can I see the working demo?
> 
> i deployed on the staging server

image
Oh, it's much much faster and better.
Thanks you

**Review by salahawk — APPROVED** [review]

**Comment by crazydevlegend** [comment]
thanks, bro

**Pull request merged**
